repositories:
  - name: strimzi
    url: https://strimzi.io/charts/
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
releases:
  - name: strimzi
    namespace: strimzi
    createNamespace: true
    chart: strimzi/strimzi-kafka-operator
    version: 0.19.0
  - name: kafka
    namespace: strimzi
    chart: incubator/raw
    values:
    - resources:
      - apiVersion: kafka.strimzi.io/v1beta1
        kind: Kafka
        metadata:
          name: my-kafka
        spec:
          kafka:
            version: 2.5.0
            replicas: 1
            listeners:
              plain: { }
              tls: { }
            config:
              offsets.topic.replication.factor: 1
              transaction.state.log.replication.factor: 1
              transaction.state.log.min.isr: 1
              log.message.format.version: "2.5"
            storage:
              type: jbod
              volumes:
                - id: 0
                  type: persistent-claim
                  size: 100Gi
                  deleteClaim: false
          zookeeper:
            replicas: 1
            storage:
              type: persistent-claim
              size: 100Gi
              deleteClaim: false
          entityOperator:
            topicOperator: { }
            userOperator: { }
