releases:
- name: frontend
  namespace: app
  createNamespace: true
  chart: ./frontend
  values:
  - ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/issuer: "letsencrypt-prod"
        nginx.org/redirect-to-https: "true"
        nginx.org/proxy-buffer-size: "8k"
      hosts:
        - host: app.{{ .Values.loadBalancer.suffix }}
          paths:
            - /
      tls:
        - secretName: app-tls
          hosts:
            - app.{{ .Values.loadBalancer.suffix }}
  - gcp:
      project: {{ .Values.gcp.project }}
- name: database-secret
  chart: incubator/raw
  namespace: app
  createNamespace: true
  values:
    - resources:
        - apiVersion: "kubernetes-client.io/v1"
          kind: ExternalSecret
          metadata:
            name: database
          spec:
            backendType: gcpSecretsManager
            projectId: {{ .Values.gcp.project }}
            data:
              - key: {{ .Values.mysql.passwordSecretName }}
                version: latest
                name: databasePassword
- name: apicast-secret
  chart: incubator/raw
  namespace: app
  createNamespace: true
  values:
    - resources:
        - apiVersion: "kubernetes-client.io/v1"
          kind: ExternalSecret
          metadata:
            name: apicast
          spec:
            backendType: gcpSecretsManager
            projectId: {{ .Values.gcp.project }}
            data:
              - key: apiCastSecretToken
                version: latest
                name: secretToken
- name: backend
  namespace: app
  createNamespace: true
  chart: ./backend
  values:
    - ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/issuer: "letsencrypt-prod"
          nginx.org/redirect-to-https: "true"
        hosts:
          - host: inventory.{{ .Values.loadBalancer.suffix }}
            paths:
              - /
        tls:
          - secretName: inventory-tls
            hosts:
              - inventory.{{ .Values.loadBalancer.suffix }}
    - gcp:
        project: {{ .Values.gcp.project }}
    - keycloak:
        url: https://keycloak.{{ .Values.loadBalancer.suffix }}/auth

- name: smtp-secret
  chart: incubator/raw
  namespace: app
  createNamespace: true
  values:
    - resources:
        - apiVersion: "kubernetes-client.io/v1"
          kind: ExternalSecret
          metadata:
            name: smtp
          spec:
            backendType: gcpSecretsManager
            projectId: {{ .Values.gcp.project }}
            data:
              - key: smtpPassword
                version: latest
                name: password
- name: new-customer
  namespace: app
  createNamespace: true
  chart: ./new-customer
  values:
    - kafka:
        brokers:
          - kafka-cluster-1-kafka-brokers.services:9092
    - smtp:
        host: smtp.gmail.com
        port: 465
        username: pete.muir@gmail.com
