releases:
- name: oauth2-proxy
  namespace: app
  createNamespace: true
  chart: stable/oauth2-proxy
  version: 3.2.2
- name: app
  namespace: app
  createNamespace: true
  chart: ./demo-app
  values:
  - ingress:
      enabled: true
      service:
        name: oauth2-proxy
        port: 80
      annotations:
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/issuer: "letsencrypt-prod"
        nginx.org/redirect-to-https: "true"
      hosts:
        - host: app.{{ .Values.loadBalancer.suffix }}
          paths:
            - /
      tls:
        - secretName: app-tls
          hosts:
            - app.{{ .Values.loadBalancer.suffix }}
  - image:
      tag: latest
