connect:
  name: debezium
  image:
    repository: pmuir/connect-debezium
    tag: 0.17.0-kafka-2.4.0
  credentials:
    secretName: connect-credentials
connectors: []
kafka:
  name: kafka-cluster-1
keycloak:
  name: demo-keycloak
  replicas: 1
  hostName: keycloak
  service:
    name: keycloak # This seems to be a static value?
    port: 8443
  realms: []
loadBalancer:
  suffix: local

