connect:
  name: demo-connect
  image:
    repository: pmuir/connect-debezium
    tag: 1.0.3
  kafka:
    name: demo-kafka
  credentials:
    secretName: connect-credentials
connectors: []
kafka:
  name: demo-kafka
  version: 2.5.0
keycloak:
  name: demo-keycloak
  replicas: 1
  hostName: keycloak
  service:
    name: keycloak
    port: 8443
loadBalancer:
  suffix: local

