apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: keycloak
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.gcp.project }}
  data:
    - key: clientId
      version: latest
      name: clientId
    - key: clientSecret
      version: latest
      name: clientSecret
