repositories:
  - name: charts.jetstack.io
    url: https://charts.jetstack.io

releases:
  - name: "cert-manager-crds"
    namespace: "{{ .Values.certManager.namespace }}"
    chart: "./charts/cert-manager-crds"
    createNamespace: true
    wait: true
