repositories:
- name: godaddy.github.io-kubernetes-external-secrets
  url: https://godaddy.github.io/kubernetes-external-secrets/

releases:
- name: "external-secrets"
  namespace: "{{ .Values.externalSecrets.namespace }}"
  createNamespace: true
  chart: "godaddy.github.io-kubernetes-external-secrets/kubernetes-external-secrets"
  version: "{{ .Values.externalSecrets.version }}"
  values:
  - serviceAccount:
      name: {{.Values.externalSecrets.kubernetesServiceAccount}}
      annotations:
        "iam.gke.io/gcp-service-account": "{{ .Values.externalSecrets.googleServiceAccount }}"
