repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
releases:
#
- name: external-dns
  namespace: {{ .Values.externalDns.namespace}}
  createNamespace: true
  chart: bitnami/external-dns
  version: 3.4.0
  values:
  - provider: google
    google:
      project: {{ .Values.gcp.project }}
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: {{ .Values.externalDns.googleServiceAccount}}
      name: {{ .Values.externalDns.kubernetesServiceAccount}}
