helmfiles:
- path: cert-manager.yaml
  values:
  - values.yaml
  - generated.yaml
- path: letsencrypt-issuers.yaml
  values:
  - values.yaml
  - generated.yaml
- path: nginx-ingress.yaml
  values:
  - values.yaml
  - generated.yaml
- path: olm-crds.yaml
- path: olm.yaml
- path: external-secrets.yaml
  values:
  - values.yaml
  - generated.yaml
- path: gcloud-sql-proxy.yaml
  values:
  - values.yaml
  - generated.yaml
- path: keycloak-gcloud-sql-proxy.yaml
  values:
    - values.yaml
    - generated.yaml
- path: strimzi.yaml
- path: keycloak.yaml
- path: apicast.yaml
- path: services.yaml