helmfiles:
  - olm-crds.yaml
  - olm.yaml
  - path: external-secrets.yaml
    values:
      - values.yaml
      - generated.yaml
  - path: gcloud-sql-proxy.yaml
    values:
      - values.yaml
      - generated.yaml
  - strimzi.yaml
  - keycloak.yaml
  - apicast.yaml
  - services.yaml