releases:
- name: "letsencrypt-issuers"
  namespace: services
  createNamespace: true
  chart: "./charts/letsencrypt-issuers"
  force: true
  values:
  - email: "{{ .Values.certManager.email}}"
    projectId: {{ .Values.gcp.project }}