repositories:
  - name: "helm.nginx.com-stable"
    url: "https://helm.nginx.com/stable"

releases:
- name: "ingress"
  namespace: {{ .Values.ingress.namespace }}
  chart: "helm.nginx.com-stable/nginx-ingress"
  version: ~0.4.3
  createNamespace: true
  values:
    - controller:
        service:
          loadBalancerIP: "{{ .Values.loadBalancer.ip }}"
