repositories:
- name: strimzi
  url: https://strimzi.io/charts/
releases:
- name: namespace-services
  # Strimzi needs to watch namespace. As this creates a namespace it will not exist yet so we use 'kube-system'
  #  which should exist in all clusters.
  chart: incubator/raw
  namespace: services
  createNamespace: true
# The strimzi installed by the OLM is missing CRDs
- name: strimzi
  namespace: strimzi
  createNamespace: true
  chart: strimzi/strimzi-kafka-operator
  version: 0.17.0
  values:
  - watchNamespaces:
    - services
