apiVersion: "networking.k8s.io/v1beta1"
kind: Ingress
metadata:
  namespace: apicast
  name: api
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.org/redirect-to-https: "true"
spec:
  rules:
    - host: api.g.bleepbleep.org.uk
      http:
        paths:
          - backend:
              serviceName: apicast-pmuir
              servicePort: 8080
            path: /
    - host: api-staging.g.bleepbleep.org.uk
      http:
        paths:
          - backend:
              serviceName: apicast-pmuir
              servicePort: 8080
            path: /

  tls:
    - hosts:
        - api.g.bleepbleep.org.uk
        - api-staging.g.bleepbleep.org.uk
      secretName: api-tls