apiVersion: v1
kind: Secret
metadata:
  name: apicast-credentials
  # The operator seems to only work on the same namespace it's installed into
  namespace: apicast
type: Opaque
stringData:
  config.json: |
    {
      "services": [
        {
          "proxy": {
            "policy_chain": [
              { "name": "apicast.policy.upstream",
                "configuration": {
                  "rules": [{
                    "regex": "/",
                    "url": "http://echo-api.3scale.net"
                  }]
                }
              }
            ]
          }
        }
      ]
    }
