### Doesn't work due to code in the apicast operator that fails if the secret already has an ownerref ###
# TODO file an issue for this
# Create this secret manually without the owner ref

# apiVersion: "kubernetes-client.io/v1"
# kind: ExternalSecret
# metadata:
#  name: apicast-credentials
#  # The operator seems to only work on the same namespace it's installed into
#  namespace: apicast
#spec:
#  backendType: gcpSecretsManager
#  projectId: {{ .Values.gcp.project }}
#  data:
#  - key: apicastAdminPortalCredentials
#    version: latest
#    name: AdminPortalURL
