apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: connect-credentials
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.gcp.project }}
  data:
    - key: {{ .Values.mysql.mysqlPropertiesSecretName }}
      version: latest
      name: debezium-mysql-credentials.properties
