apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: {{ .Values.connect.name }}
  annotations:
    # use-connector-resources configures this KafkaConnect
    # to use KafkaConnector resources to avoid
    # needing to call the Connect REST API directly
    strimzi.io/use-connector-resources: "true"
spec:
  image: {{ .Values.connect.image.repository }}:{{ .Values.connect.image.tag }}
  replicas: 1
  bootstrapServers: {{ .Values.connect.kafka.name }}-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: {{ .Values.connect.kafka.name }}-cluster-ca-cert
        certificate: ca.crt
  config:
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
  externalConfiguration:
    volumes:
      - name: connector-config
        secret:
          secretName: {{ .Values.connect.credentials.secretName }}