apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: {{ .Values.kafka.name }}
spec:
  kafka:
    replicas: 1
    listeners:
      plain: { }
      tls: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 100Gi
          deleteClaim: false
  zookeeper:
    replicas: 2
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
    readinessProbe:
      timeoutSeconds: 30
    livenessProbe:
      timeoutSeconds: 30
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
  entityOperator:
    topicOperator: { }
    userOperator: { }