apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: {{ .Values.keycloak.name }}
  labels:
    keycloak.org/keycloak: {{ .Values.keycloak.name }}
spec:
  instances: {{ .Values.keycloak.replicas }}
  externalAccess:
    enabled: false
  externalDatabase:
    enabled: true